# Generated by Django 5.2.7 on 2025-10-01 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.IntegerField()),
                ('rg', models.IntegerField()),
                ('email', models.TextField()),
                ('telefone', models.IntegerField()),
                ('endereco', models.TextField()),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
